
<?php

// require_once __DIR__ . '/vendor/autoload.php';

// autoload.php @generated by Composer
use Spipu\Html2Pdf\Html2Pdf;
// $html2pdf = new Html2Pdf();
// $html2pdf = new HTML2PDF('L', 'A4', 'en');
// 86mm x 54mm
$width_in_inches = 86;
$height_in_inches = 54;



// $width_in_mm = $width_in_inches * 25.4;
// $height_in_mm = $height_in_inches * 25.4;

// $html2pdf = new HTML2PDF('L', array($width_in_inches, $height_in_inches), 'en', true, 'UTF-8', array(0, 0, 0, 0));
$html2pdf = new HTML2PDF('P', 'A4', 'en');

//$html2pdf->setDefaultFont('aealarabiya');
// ---------------------------------------------------------

// set font


//$html2pdf->SetFontSize(10);
//$html2pdf->setDefaultFont('aefurat', '', 12);

$html2pdf->setDefaultFont('dejavusans', '', 12);
$html2pdf->pdf->SetDisplayMode('real');

//$html2pdf->setDefaultFont('aealarabiya');
//$my_html = "<style>" . file_get_contents(__DIR__ . '/style.css') . "</style>";

$my_html = "<style>" . file_get_contents(base_path('public/css/styleold.css')) . "</style>";

$html2pdf->WriteHTML($my_html);
// $html2pdf->setModeDebug();
//<span class="text-md">رقم الجوال: ' . $card->citizen->phone . '  </span><br>

$html2pdf->writeHTML('


               <img class="background-image" src="'.'uploads/0001_new.jpg'.'"        alt="">


                <div class="left-div" style="line-height: 1;" style="">
                <img class="mx-auto" src="' . 'uploads/' . $citizen->image . '" alt="" width="150" style="margin-left:2px; margin-top: 2px;">
                <br>
                </div>

                    <div class="new-div" style="padding-left: 1px; >

                    <div class="info"  text-align: left; font-size: 12pt; ">

                    <table align="center">

                      <tr>
                         <th colspan="2">' . $citizen->first_name . '<br>' . $citizen->first_name_en.' ' .''.$citizen->second_name_en.' ' .''.$citizen->third_name_en.' ' .''.$citizen->fourth_name_en. '</th>
                      </tr>
                      <tr>
                        <td class="a">الأم<br>
                        (Mothers name/Anne)
                        </td>
                        <td> ' . $citizen->mother_name_ar . '<br>' .$citizen->mother_name_en . '</td>
                      </tr>
                      <tr>
                        <td class="a">القبيلة
                        <br>Tribe(kabile):</td>
                        <td>' .$citizen->tripe->name_ar . '<br>' .$citizen->tripe->name_en . '</td>
                      </tr>

                       <tr>
                        <td class="a">العنوان <br>
                        Place of residence<br>(adres):</td>
                        <td> ' . $citizen->addresses->first()->address1 . '</td>
                      </tr>

                      <tr>
                        <td class="a">مكان وتاريخ الميلاد <br>
                        Place and birth date:<br>(Doğum yeri ve tarihi):</td>
                        <td>' . $citizen->place_of_birth." ". Carbon\Carbon::parse($citizen->birth_date)->format('Y') . '</td>

                      </tr>
                      <tr>

                       <td class="a">الجنس <br>
                       Gender:(Cinsiyet)</td>
                        <td>' . $citizen->gender.'</td>

                      </tr>

              <tr>

                       <td class="a">الحالة الإجتماعية <br>
                       marital status:(Medeni hal)</td>
                        <td>' . $citizen->marital_status.'</td>

                      </tr>


                  <tr>

                       <td class="a">الجوال <br>
                       phone (telefon):</td>
                        <td>' . $citizen->phone.'</td>

                      </tr>
                  <tr>

                       <td class="a">المهنة <br>
                       job(Görev):</td>
                        <td>' . $citizen->job->name.'</td>

                      </tr>



            <tr>

                       <td class="a">العنوان <br>
                       address(adres):</td>
                        <td>' . $address->address1.'</td>

                      </tr>

                    <tr>

                       <td class="a">الشارع <br>
                       street(sokak):</td>
                        <td>' .$address->street.'</td>

                      </tr>

                   <tr>

                       <td class="a">العنوان 2 <br>
                       address2 (adres2):</td>
                        <td>' .$address->address2.'</td>

                      </tr>

                      <tr>

                       <td class="a">الرمز البريدي  <br>
                       Postal code(posta kodu):</td>
                        <td>' .$address->code.'</td>

                      </tr>
            <tr>

                       <td class="a">الدولة <br>
                       Country name(ülke adı):</td>
                        <td>' .$citizen->country->name.'</td>

                      </tr>
               <tr>

                       <td class="a">النسب <br>
                       descent(anne):</td>
                        <td>' .$citizen->descent->name.'</td>

                      </tr>
                       <tr>

                       <td class="a">الحسب<br>
                       arithmetic(aritmetik):</td>
                        <td>' .$citizen->arithmetic->name.'</td>

                      </tr>

             <tr>

                       <td class="a">اسم الضامن  <br>
                       Gurantors fullname<br>
                       (Garantörlerin tam adı):</td>
                        <td>' .$gurantors->fullname.'</td>

                      </tr>
               <tr>

                       <td class="a">Gurantors card number:</td>
                        <td>' .$gurantors->card_number.'</td>

                      </tr>
                  <tr>

                       <td class="a">Gurantors Phone:</td>
                        <td>' .$gurantors->phone.'</td>

                      </tr>



                    </table>


                    </div>
                </div>


');
//$html2pdf->output('myPdf.pdf');
ob_end_clean();
//$html2pdf->Output('I');
$html2pdf->Output('doc.pdf', 'I')
?>
